services:
  backend:
    build:
      context: ./Back
      dockerfile: Dockerfile
    image: catalogo_de_productos_backend
    ports:
      - "8080:8080"
    environment:
      - ASPNETCORE_ENVIRONMENT=Production
      - ASPNETCORE_URLS=http://+:8080
      - ConnectionStrings__DefaultConnection=Server=db;Database=catalogoDb;User=sa;Password=Vale*Pru578;TrustServerCertificate=True;
    depends_on:
      - db
    networks:
      - app-network

  frontend:
    build:
      context: ./Front/catalogo_de_productos
      dockerfile: Dockerfile
    image: catalogo_de_productos_frontend
    ports:
      - "80:80"
    depends_on:
      - backend
    networks:
      - app-network

  db:
    image: mcr.microsoft.com/mssql/server:2022-latest
    environment:
      - ACCEPT_EULA=Y
      - SA_PASSWORD=Vale*Pru578
    ports:
      - "1433:1433"
    volumes:
      - sql-data:/var/opt/mssql
    networks:
      - app-network

networks:
  app-network:
    driver: bridge

volumes:
  sql-data: